import type { BloomIntensity, FloweringPlant } from "./flowering-plants";

function bm(...entries: [number, BloomIntensity][]) {
  return Object.fromEntries(entries) as Partial<Record<number, BloomIntensity>>;
}

/** Rozszerzenie bazy kwitnienia — gatunki uzupełniające katalog do 100+ pozycji */
export const FLOWERING_PLANTS_EXTRA: FloweringPlant[] = [
  // —— Drzewa ——
  {
    id: "swidosliwa",
    name: "Świdośliwa",
    latinName: "Amelanchier lamarckii",
    category: "krzew",
    bloomMonths: bm([4, "peak"], [5, "light"]),
    colors: ["bialy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: true,
    light: ["pelne-slonce", "polcien"],
    height: "4–8 m",
    description: "Białe kwiaty przed liśćmi — małe jabłuszka jesienią i pomarańczowe przebarwienie.",
  },
  {
    id: "jarzebin",
    name: "Jarzębin pospolity",
    latinName: "Sorbus aucuparia",
    category: "drzewo",
    bloomMonths: bm([5, "peak"], [6, "light"]),
    colors: ["bialy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: true,
    light: ["pelne-slonce"],
    height: "8–15 m",
    description: "Białe kwiatostany w maju — czerwone jagody dla ptaków jesienią.",
  },
  {
    id: "robinia",
    name: "Robinia akacjowa",
    latinName: "Robinia pseudoacacia",
    category: "drzewo",
    bloomMonths: bm([5, "peak"], [6, "peak"]),
    colors: ["bialy", "rozowy"],
    scent: "strong",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "15–25 m",
    description: "Pachnące białe grona w czerwcu — jeden z najważniejszych miododajnych drzew.",
  },
  {
    id: "tulipowiec",
    name: "Tulipowiec amerykański",
    latinName: "Liriodendron tulipifera",
    category: "drzewo",
    bloomMonths: bm([5, "peak"], [6, "light"]),
    colors: ["zolty", "pomaranczowy", "mieszany"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: true,
    light: ["pelne-slonce"],
    height: "20–35 m",
    description: "Kwiaty w kształcie tulipana na szczycie dużego drzewa — żółto-pomarańczowe.",
  },
  {
    id: "grab",
    name: "Grab pospolity",
    latinName: "Carpinus betulus",
    category: "drzewo",
    bloomMonths: bm([4, "peak"], [5, "light"]),
    colors: ["zolty", "mieszany"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: true,
    light: ["pelne-slonce", "polcien"],
    height: "15–25 m",
    description: "Dyskretne kocieki w kwietniu — popularny na żywopłoty, jesienne przebarwienie.",
    relatedLink: { href: "/kalkulator-zywoplotu", label: "Kalkulator żywopłotu" },
  },
  {
    id: "klon-jawor",
    name: "Klon jawor",
    latinName: "Acer pseudoplatanus",
    category: "drzewo",
    bloomMonths: bm([4, "peak"], [5, "peak"]),
    colors: ["zolty", "mieszany"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: true,
    light: ["pelne-slonce"],
    height: "20–30 m",
    description: "Żółto-zielone kwiaty wiosną — miododajny, charakterystyczne skrzydlate owoce.",
  },
  {
    id: "olcha",
    name: "Olsza czarna",
    latinName: "Alnus glutinosa",
    category: "drzewo",
    bloomMonths: bm([3, "peak"], [4, "light"]),
    colors: ["zolty", "mieszany"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: false,
    light: ["pelne-slonce", "polcien"],
    height: "15–25 m",
    description: "Wczesne kocieki w marcu — rośnie na wilgotnych glebach, miododajna.",
  },
  {
    id: "sliwa",
    name: "Śliwa domowa",
    latinName: "Prunus domestica",
    category: "drzewo",
    bloomMonths: bm([4, "peak"], [5, "light"]),
    colors: ["bialy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "4–8 m",
    description: "Białe kwiaty przed liśćmi — użyteczne i ozdobne drzewo owocowe.",
  },
  {
    id: "grusza",
    name: "Grusza pospolita",
    latinName: "Pyrus communis",
    category: "drzewo",
    bloomMonths: bm([4, "peak"], [5, "peak"]),
    colors: ["bialy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "5–12 m",
    description: "Białe kwiaty w kwietniu i maju — wymaga zapylaczy do owoców.",
  },
  {
    id: "morela",
    name: "Morela pospolita",
    latinName: "Prunus armeniaca",
    category: "drzewo",
    bloomMonths: bm([4, "peak"]),
    colors: ["bialy", "rozowy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "4–6 m",
    description: "Różowo-białe kwiaty wczesną wiosną — wrażliwa na późne przymrozki.",
  },

  // —— Krzewy ——
  {
    id: "krzewuszka",
    name: "Krzewuszka",
    latinName: "Spiraea japonica",
    category: "krzew",
    bloomMonths: bm([6, "peak"], [7, "peak"], [8, "light"]),
    colors: ["rozowy", "bialy", "czerwony"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: true,
    light: ["pelne-slonce"],
    height: "0,5–1,5 m",
    description: "Różowe lub białe kwiatostany całe lato — niski krzew na rabaty i skarpy.",
  },
  {
    id: "weigelia",
    name: "Weigelia",
    latinName: "Weigela florida",
    category: "krzew",
    bloomMonths: bm([5, "peak"], [6, "peak"], [7, "light"]),
    colors: ["rozowy", "czerwony", "bialy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce", "polcien"],
    height: "1,5–3 m",
    description: "Różowe dzwonki w maju i czerwcu — powtarza kwitnienie po przycięciu.",
  },
  {
    id: "jasminek",
    name: "Jaśminowiec wonny",
    latinName: "Philadelphus coronarius",
    category: "krzew",
    bloomMonths: bm([6, "peak"], [7, "peak"]),
    colors: ["bialy"],
    scent: "strong",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce", "polcien"],
    height: "2–3 m",
    description: "Intensywnie pachnące białe kwiaty w czerwcu — klasyk ogrodów wiejskich.",
  },
  {
    id: "rozanecznik",
    name: "Różanecznik",
    latinName: "Rhododendron",
    category: "krzew",
    bloomMonths: bm([5, "peak"], [6, "peak"]),
    colors: ["rozowy", "fioletowy", "bialy", "czerwony", "mieszany"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["polcien", "cien"],
    height: "1–4 m",
    description: "Efektowne kwiaty w maju — wymaga kwaśnej, przepuszczalnej gleby.",
  },
  {
    id: "pecherznica",
    name: "Pęcherznica",
    latinName: "Physocarpus opulifolius",
    category: "krzew",
    bloomMonths: bm([5, "peak"], [6, "light"]),
    colors: ["bialy", "rozowy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: true,
    light: ["pelne-slonce", "polcien"],
    height: "1,5–3 m",
    description: "Białe kwiaty i purpurowe liście — odmiany „Diabolo” i „Dart's Gold”.",
  },
  {
    id: "ostrokrzew",
    name: "Ostrokrzew kolczasty",
    latinName: "Ilex aquifolium",
    category: "krzew",
    bloomMonths: bm([5, "light"], [6, "peak"]),
    colors: ["bialy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: false,
    light: ["polcien", "cien"],
    height: "5–12 m",
    description: "Drobne białe kwiaty — czerwone jagody zimą na żeńskich okazach.",
  },
  {
    id: "borowka",
    name: "Borówka wysoka",
    latinName: "Vaccinium corymbosum",
    category: "krzew",
    bloomMonths: bm([5, "peak"], [6, "light"]),
    colors: ["bialy", "rozowy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: true,
    light: ["pelne-slonce", "polcien"],
    height: "1–2 m",
    description: "Dzwonkowate kwiaty w maju — jagody latem, czerwone liście jesienią.",
  },
  {
    id: "malina",
    name: "Malina",
    latinName: "Rubus idaeus",
    category: "krzew",
    bloomMonths: bm([6, "peak"], [7, "peak"], [8, "light"]),
    colors: ["bialy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: false,
    light: ["pelne-slonce", "polcien"],
    height: "1–2 m",
    description: "Białe kwiaty w czerwcu — owoce i kwiaty na jednej roślinie.",
  },
  {
    id: "tamaryszek",
    name: "Tamaryszek",
    latinName: "Tamarix ramosissima",
    category: "krzew",
    bloomMonths: bm([6, "peak"], [7, "peak"], [8, "peak"], [9, "light"]),
    colors: ["rozowy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "2–4 m",
    description: "Różowe kwiaty całe lato — toleruje sól i suszę, nad wodą.",
  },
  {
    id: "mudrzal",
    name: "Mudrzal",
    latinName: "Rhus typhina",
    category: "krzew",
    bloomMonths: bm([6, "peak"], [7, "light"]),
    colors: ["zolty", "mieszany"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: true,
    light: ["pelne-slonce"],
    height: "3–5 m",
    description: "Żółte kwiatostany i charakterystyczne czerwone „szczotki” jesienią.",
  },

  // —— Byliny ——
  {
    id: "naparstnica",
    name: "Naparstnica",
    latinName: "Digitalis purpurea",
    category: "bylina",
    bloomMonths: bm([6, "peak"], [7, "peak"]),
    colors: ["fioletowy", "rozowy", "bialy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["polcien", "cien"],
    height: "80–150 cm",
    description: "Wysokie wieże fioletowych dzwonków — cień, wilgotna gleba. Trująca!",
  },
  {
    id: "zeniszek",
    name: "Żeniszek",
    latinName: "Aquilegia vulgaris",
    category: "bylina",
    bloomMonths: bm([5, "peak"], [6, "peak"]),
    colors: ["fioletowy", "niebieski", "rozowy", "bialy", "czerwony"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["polcien", "cien"],
    height: "40–80 cm",
    description: "Spore kwiaty z „ostrogami” — samosieje się w naturalistycznych rabatach.",
  },
  {
    id: "irys",
    name: "Irys niemiecki",
    latinName: "Iris germanica",
    category: "bylina",
    bloomMonths: bm([5, "peak"], [6, "peak"]),
    colors: ["fioletowy", "niebieski", "zolty", "bialy", "mieszany"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "60–100 cm",
    description: "Klasyczne kwiaty w maju i czerwcu — żółto-fioletowe odmiany bearded iris.",
  },
  {
    id: "lupina",
    name: "Łubin",
    latinName: "Lupinus polyphyllus",
    category: "bylina",
    bloomMonths: bm([6, "peak"], [7, "peak"]),
    colors: ["fioletowy", "rozowy", "bialy", "czerwony", "zolty"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "60–120 cm",
    description: "Wysokie kłosy wielobarwnych kwiatów — azotofiksujący, do naturalistycznych rabat.",
  },
  {
    id: "dabrowka",
    name: "Dąbrówka",
    latinName: "Geranium",
    category: "bylina",
    bloomMonths: bm([5, "peak"], [6, "peak"], [7, "light"]),
    colors: ["niebieski", "rozowy", "bialy", "fioletowy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: true,
    light: ["pelne-slonce", "polcien"],
    height: "20–60 cm",
    description: "Długie kwitnienie od maja — „Rozanne” i „Johnson's Blue” to klasyki.",
  },
  {
    id: "bergenia",
    name: "Bergenia",
    latinName: "Bergenia cordifolia",
    category: "bylina",
    bloomMonths: bm([4, "peak"], [5, "peak"]),
    colors: ["rozowy", "bialy", "czerwony"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: true,
    light: ["pelne-slonce", "polcien", "cien"],
    height: "30–50 cm",
    description: "Grube liście i różowe kwiaty wczesną wiosną — czerwone przebarwienie zimą.",
  },
  {
    id: "barwinek",
    name: "Barwinek",
    latinName: "Vinca minor",
    category: "bylina",
    bloomMonths: bm([4, "peak"], [5, "peak"]),
    colors: ["niebieski", "bialy", "fioletowy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["cien", "polcien"],
    height: "10–20 cm",
    description: "Niebieskie kwiaty i zimozielone liście — pokrywa glebę w cieniu drzew.",
  },
  {
    id: "ajuga",
    name: "Dąbrówka ajuga",
    latinName: "Ajuga reptans",
    category: "bylina",
    bloomMonths: bm([5, "peak"], [6, "light"]),
    colors: ["niebieski", "fioletowy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["polcien", "cien"],
    height: "10–20 cm",
    description: "Niebieskie kwiaty nad purpurowymi liśćmi — roślina okrywowa w cieniu.",
  },
  {
    id: "krwawnik",
    name: "Krwawnik",
    latinName: "Achillea millefolium",
    category: "bylina",
    bloomMonths: bm([6, "peak"], [7, "peak"], [8, "peak"]),
    colors: ["bialy", "zolty", "rozowy", "czerwony"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "40–80 cm",
    description: "Płaskie kwiatostany całe lato — suszone kwiaty zimą, miododajny.",
  },
  {
    id: "perowka",
    name: "Przetacznik",
    latinName: "Veronica spicata",
    category: "bylina",
    bloomMonths: bm([6, "peak"], [7, "peak"], [8, "light"]),
    colors: ["niebieski", "rozowy", "bialy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "30–60 cm",
    description: "Niebieskie lub różowe kłosy — niska bylina na słoneczne rabaty.",
  },
  {
    id: "zlocien",
    name: "Złocień",
    latinName: "Solidago canadensis",
    category: "bylina",
    bloomMonths: bm([8, "peak"], [9, "peak"], [10, "light"]),
    colors: ["zolty"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "80–150 cm",
    description: "Żółte kwiaty jesienią — miododajny, naturalistyczny styl prairi.",
  },
  {
    id: "zajecza-kapusta",
    name: "Zajęcza kapusta",
    latinName: "Alchemilla mollis",
    category: "bylina",
    bloomMonths: bm([6, "peak"], [7, "peak"], [8, "light"]),
    colors: ["zolty", "mieszany"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce", "polcien"],
    height: "30–50 cm",
    description: "Żółto-zielone kwiatostany z kropelkami rosy — miękkie, filcowate liście.",
  },
  {
    id: "salvia",
    name: "Szałwia ozdobna",
    latinName: "Salvia nemorosa",
    category: "bylina",
    bloomMonths: bm([6, "peak"], [7, "peak"], [8, "peak"], [9, "light"]),
    colors: ["fioletowy", "niebieski", "rozowy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "40–60 cm",
    description: "Fioletowo-niebieskie kwiaty całe lato — przycina po kwitnieniu dla drugiej fali.",
  },
  {
    id: "maciejka",
    name: "Pierwiosnek",
    latinName: "Primula vulgaris",
    category: "bylina",
    bloomMonths: bm([3, "peak"], [4, "peak"], [5, "light"]),
    colors: ["zolty", "rozowy", "bialy", "fioletowy", "czerwony"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["polcien"],
    height: "10–20 cm",
    description: "Wczesnowiosenne kwiaty w wielu kolorach — pod drzewa i do skalniaków.",
  },
  {
    id: "tiarella",
    name: "Tiarella",
    latinName: "Tiarella cordifolia",
    category: "bylina",
    bloomMonths: bm([5, "peak"], [6, "light"]),
    colors: ["bialy", "rozowy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: true,
    light: ["cien", "polcien"],
    height: "20–40 cm",
    description: "Białe kwiaty jak pianki — dekoracyjne liście, do cienistych rabat.",
  },
  {
    id: "dalia",
    name: "Dalia",
    latinName: "Dahlia",
    category: "bylina",
    bloomMonths: bm([7, "peak"], [8, "peak"], [9, "peak"], [10, "light"]),
    colors: ["czerwony", "rozowy", "zolty", "pomaranczowy", "bialy", "fioletowy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "40–120 cm",
    description: "Obfite kwiaty od lipca do przymrozków — wykop bulwy na zimę lub okryj.",
  },
  {
    id: "piwonia-drzewiasta",
    name: "Piwonia drzewiasta",
    latinName: "Paeonia suffruticosa",
    category: "krzew",
    bloomMonths: bm([5, "peak"], [6, "light"]),
    colors: ["rozowy", "czerwony", "bialy", "fioletowy"],
    scent: "strong",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce", "polcien"],
    height: "1–2 m",
    description: "Wielkie pachnące kwiaty w maju — krzewiasta piwonia, okrywaj zimą.",
  },
  {
    id: "groszek-pachnacy",
    name: "Groszek pachnący",
    latinName: "Lathyrus odoratus",
    category: "roczna",
    bloomMonths: bm([6, "peak"], [7, "peak"], [8, "peak"], [9, "light"]),
    colors: ["rozowy", "fioletowy", "bialy", "czerwony", "mieszany"],
    scent: "strong",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "150–200 cm",
    description: "Pachnące kwiaty na podporach — klasyk letnich ogrodów i bukietów.",
  },
  {
    id: "manuczek",
    name: "Manuczek",
    latinName: "Centranthus ruber",
    category: "bylina",
    bloomMonths: bm([5, "peak"], [6, "peak"], [7, "peak"], [8, "light"]),
    colors: ["rozowy", "bialy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "60–90 cm",
    description: "Różowe kwiaty całe lato — motyle, samosieje na suchych skarpach.",
  },

  // —— Cebulowe ——
  {
    id: "hiacynt",
    name: "Hiacynt",
    latinName: "Hyacinthus orientalis",
    category: "cebula",
    bloomMonths: bm([4, "peak"], [5, "light"]),
    colors: ["fioletowy", "rozowy", "bialy", "niebieski", "czerwony"],
    scent: "strong",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce", "polcien"],
    height: "20–30 cm",
    description: "Intensywnie pachnące kwiaty wiosną — sadź jesienią w grupach.",
  },
  {
    id: "muskari",
    name: "Muskari",
    latinName: "Muscari armeniacum",
    category: "cebula",
    bloomMonths: bm([4, "peak"], [5, "light"]),
    colors: ["niebieski", "fioletowy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce", "polcien"],
    height: "15–25 cm",
    description: "Niebieskie grona jak winogrona — wczesna wiosna, mnoży się samo.",
  },
  {
    id: "szafirek",
    name: "Szafirek",
    latinName: "Scilla siberica",
    category: "cebula",
    bloomMonths: bm([3, "peak"], [4, "light"]),
    colors: ["niebieski"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["polcien", "cien"],
    height: "10–15 cm",
    description: "Intensywnie niebieskie kwiaty w marcu — pod drzewa liściaste.",
  },
  {
    id: "snezjnik",
    name: "Śnieżnik",
    latinName: "Leucojum vernum",
    category: "cebula",
    bloomMonths: bm([3, "peak"], [4, "light"]),
    colors: ["bialy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["polcien", "cien"],
    height: "15–25 cm",
    description: "Większy kuzyn śnieżyczki — białe dzwonki z zielonymi plamkami.",
  },
  {
    id: "czosnek-ozdobny",
    name: "Czosnek ozdobny",
    latinName: "Allium",
    category: "cebula",
    bloomMonths: bm([5, "peak"], [6, "peak"], [7, "light"]),
    colors: ["fioletowy", "rozowy", "bialy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "30–120 cm",
    description: "Kuliste kwiatostany w maju i czerwcu — „Globemaster” i „Purple Sensation”.",
  },
  {
    id: "zygzakowiec",
    name: "Zygokaktus",
    latinName: "Cyclamen hederifolium",
    category: "cebula",
    bloomMonths: bm([8, "light"], [9, "peak"], [10, "peak"]),
    colors: ["rozowy", "bialy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["polcien", "cien"],
    height: "10–15 cm",
    description: "Różowe kwiaty jesienią pod drzewami — dekoracyjne srebrzaste liście.",
  },
  {
    id: "krokus-jesienny",
    name: "Krokus jesienny",
    latinName: "Crocus speciosus",
    category: "cebula",
    bloomMonths: bm([9, "peak"], [10, "peak"]),
    colors: ["fioletowy", "niebieski"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "8–12 cm",
    description: "Fioletowe kwiaty jesienią — przedłuża sezon kwitnienia ogrodu.",
  },

  // —— Pnącza ——
  {
    id: "roza-pnaca",
    name: "Róża pnąca",
    latinName: "Rosa",
    category: "pnacze",
    bloomMonths: bm([6, "peak"], [7, "peak"], [8, "peak"], [9, "light"]),
    colors: ["rozowy", "czerwony", "bialy", "zolty", "pomaranczowy"],
    scent: "strong",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "pnącze 2–5 m",
    description: "Obfite kwitnienie na pergoli — „New Dawn”, „Alchymist” i inne odmiany.",
  },
  {
    id: "aktinidia",
    name: "Aktinidia",
    latinName: "Actinidia kolomikta",
    category: "pnacze",
    bloomMonths: bm([5, "peak"], [6, "light"]),
    colors: ["bialy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: false,
    light: ["pelne-slonce", "polcien"],
    height: "pnącze 3–6 m",
    description: "Białe kwiaty i jadalne mini-kiwi — trójkolorowe liście (róż, biel, zieleń).",
  },
  {
    id: "honeysuckle",
    name: "Wiciokrew",
    latinName: "Lonicera periclymenum",
    category: "pnacze",
    bloomMonths: bm([6, "peak"], [7, "peak"], [8, "light"]),
    colors: ["bialy", "zolty", "rozowy"],
    scent: "strong",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: false,
    light: ["polcien"],
    height: "pnącze 2–4 m",
    description: "Pachnące kwiaty wieczorem — przyciąga ćmy i motyle.",
  },

  // —— Roczne ——
  {
    id: "aksamitka",
    name: "Aksamitka",
    latinName: "Tagetes",
    category: "roczna",
    bloomMonths: bm([6, "peak"], [7, "peak"], [8, "peak"], [9, "peak"], [10, "light"]),
    colors: ["zolty", "pomaranczowy", "czerwony"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "20–80 cm",
    description: "Żółte i pomarańczowe kwiaty do października — odstrasza niektóre szkodniki.",
  },
  {
    id: "nasturcja",
    name: "Nasturcja",
    latinName: "Tropaeolum majus",
    category: "roczna",
    bloomMonths: bm([6, "peak"], [7, "peak"], [8, "peak"], [9, "light"]),
    colors: ["pomaranczowy", "zolty", "czerwony"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "30–40 cm",
    description: "Jadalne kwiaty i liście — pomarańczowe płatki na rabatach i w donicach.",
  },
  {
    id: "slonecznik",
    name: "Słonecznik",
    latinName: "Helianthus annuus",
    category: "roczna",
    bloomMonths: bm([7, "peak"], [8, "peak"], [9, "light"]),
    colors: ["zolty", "pomaranczowy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "1–3 m",
    description: "Wielkie żółte kwiaty śledzą słońce — nasiona dla ptaków jesienią.",
  },
  {
    id: "mak",
    name: "Mak",
    latinName: "Papaver orientale",
    category: "bylina",
    bloomMonths: bm([5, "peak"], [6, "peak"]),
    colors: ["czerwony", "rozowy", "pomaranczowy", "bialy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "60–90 cm",
    description: "Papierowe płatki w maju — krótkie, spektakularne kwitnienie.",
  },
  {
    id: "czarnuszka",
    name: "Czarnuszka",
    latinName: "Nigella damascena",
    category: "roczna",
    bloomMonths: bm([6, "peak"], [7, "peak"], [8, "light"]),
    colors: ["niebieski", "bialy", "rozowy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "40–60 cm",
    description: "Niebieskie kwiaty i ozdobne torebki nasienne — samosieje się.",
  },
  {
    id: "nagietek",
    name: "Nagietek",
    latinName: "Calendula officinalis",
    category: "roczna",
    bloomMonths: bm([6, "peak"], [7, "peak"], [8, "peak"], [9, "peak"], [10, "light"]),
    colors: ["pomaranczowy", "zolty"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "30–60 cm",
    description: "Pomarańczowe kwiaty od czerwca — jadalne, lecznicze, długie kwitnienie.",
  },
  {
    id: "petunia",
    name: "Petunia",
    latinName: "Petunia × hybrida",
    category: "roczna",
    bloomMonths: bm([6, "peak"], [7, "peak"], [8, "peak"], [9, "peak"]),
    colors: ["rozowy", "fioletowy", "bialy", "czerwony", "niebieski"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "20–40 cm",
    description: "Obfite kwitnienie w donicach i skrzynkach — regularne nawożenie.",
  },
  {
    id: "lobelia",
    name: "Lobelia",
    latinName: "Lobelia erinus",
    category: "roczna",
    bloomMonths: bm([6, "peak"], [7, "peak"], [8, "peak"], [9, "light"]),
    colors: ["niebieski", "bialy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce", "polcien"],
    height: "15–25 cm",
    description: "Intensywnie niebieskie kwiaty — zwisające odmiany do skrzynek balkonowych.",
  },
  {
    id: "zinnia",
    name: "Cynia",
    latinName: "Zinnia elegans",
    category: "roczna",
    bloomMonths: bm([7, "peak"], [8, "peak"], [9, "peak"], [10, "light"]),
    colors: ["czerwony", "rozowy", "zolty", "pomaranczowy", "bialy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "40–90 cm",
    description: "Jaskrawe kwiaty na lato i jesień — motyle, długie kwitnienie do przymrozków.",
  },
  {
    id: "kanna",
    name: "Kanna",
    latinName: "Canna indica",
    category: "bylina",
    bloomMonths: bm([7, "peak"], [8, "peak"], [9, "peak"]),
    colors: ["czerwony", "zolty", "pomaranczowy", "rozowy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "80–150 cm",
    description: "Tropikalne kwiaty i duże liście — wykop kłącza na zimę w chłodnych rejonach.",
  },
];
