import type { BloomIntensity, FloweringPlant } from "./flowering-plants";

function bm(...entries: [number, BloomIntensity][]) {
  return Object.fromEntries(entries) as Partial<Record<number, BloomIntensity>>;
}

/** Faza 3 — rozbudowa do 200+ gatunków */
export const FLOWERING_PLANTS_PHASE3: FloweringPlant[] = [
  {
    id: "jesion-wyniosly",
    name: "Jesion wyniosły",
    latinName: "Fraxinus excelsior",
    category: "drzewo",
    bloomMonths: bm([4, "light"], [5, "peak"]),
    colors: ["zolty"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: true,
    light: ["pelne-slonce"],
    height: "25–35 m",
    description: "Kwitnienie niepozorne w maju — miododajne kwiaty przed liśćmi.",
  },
  {
    id: "kasztan-jadalny",
    name: "Kasztan jadalny",
    latinName: "Castanea sativa",
    category: "drzewo",
    bloomMonths: bm([6, "peak"], [7, "light"]),
    colors: ["bialy", "zolty"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: true,
    light: ["pelne-slonce"],
    height: "20–30 m",
    description: "Białe kwiaty w gronie — jesienne owoce i złote liście.",
  },
  {
    id: "klon-srebrzysty",
    name: "Klon srebrzysty",
    latinName: "Acer saccharinum",
    category: "drzewo",
    bloomMonths: bm([3, "light"], [4, "peak"]),
    colors: ["zolty"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: true,
    light: ["pelne-slonce"],
    height: "20–30 m",
    description: "Zielono-żółte kwiaty przed liśćmi — srebrzyste od spodu liście.",
  },
  {
    id: "modrzew-europejski",
    name: "Modrzew europejski",
    latinName: "Larix decidua",
    category: "drzewo",
    bloomMonths: bm([4, "peak"]),
    colors: ["rozowy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: true,
    light: ["pelne-slonce"],
    height: "30–40 m",
    description: "Różowe szyszki kwiatowe — jedyne iglaste liściaste w Polsce.",
  },
  {
    id: "sosna-zwyczajna",
    name: "Sosna zwyczajna",
    latinName: "Pinus sylvestris",
    category: "drzewo",
    bloomMonths: bm([5, "peak"]),
    colors: ["zolty"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "20–35 m",
    description: "Żółte kwiaty męskie w maju — charakterystyczna kora pomarańczowa.",
  },
  {
    id: "swierk-pospolity",
    name: "Świerk pospolity",
    latinName: "Picea abies",
    category: "drzewo",
    bloomMonths: bm([5, "peak"]),
    colors: ["czerwony", "zolty"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce", "polcien"],
    height: "30–50 m",
    description: "Czerwono-żółte szyszki kwiatowe — klasyczne drzewo leśne.",
  },
  {
    id: "buk-zwyczajny",
    name: "Buk zwyczajny",
    latinName: "Fagus sylvatica",
    category: "drzewo",
    bloomMonths: bm([4, "light"], [5, "peak"]),
    colors: ["zolty"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: true,
    light: ["pelne-slonce", "polcien"],
    height: "25–40 m",
    description: "Zielonkawe kwiaty w maju — miedziane liście jesienią.",
  },
  {
    id: "wiaz-maly",
    name: "Wiąz mały",
    latinName: "Ulmus minor",
    category: "drzewo",
    bloomMonths: bm([3, "light"], [4, "peak"]),
    colors: ["zolty"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "15–25 m",
    description: "Czerwone kwiaty przed liśćmi — odporne na choroby.",
  },
  {
    id: "topola-biala",
    name: "Topola biała",
    latinName: "Populus alba",
    category: "drzewo",
    bloomMonths: bm([3, "peak"], [4, "light"]),
    colors: ["czerwony"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "20–30 m",
    description: "Czerwone kwiaty męskie wczesną wiosną — szybki wzrost.",
  },
  {
    id: "dab-czerwony",
    name: "Dąb czerwony",
    latinName: "Quercus rubra",
    category: "drzewo",
    bloomMonths: bm([4, "light"], [5, "peak"]),
    colors: ["zolty"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: true,
    light: ["pelne-slonce"],
    height: "25–30 m",
    description: "Długie kwiaty męskie — intensywne czerwone liście jesienią.",
  },
  {
    id: "olmo-wyniosly",
    name: "Olmo wyniosły",
    latinName: "Ulmus laevis",
    category: "drzewo",
    bloomMonths: bm([3, "peak"], [4, "light"]),
    colors: ["zolty", "czerwony"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "20–30 m",
    description: "Czerwone kwiaty przed liśćmi — dobrze znosi wilgoć.",
  },
  {
    id: "jodla-pospolita",
    name: "Jodła pospolita",
    latinName: "Abies alba",
    category: "drzewo",
    bloomMonths: bm([5, "peak"]),
    colors: ["zolty", "czerwony"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["polcien", "cien"],
    height: "40–50 m",
    description: "Stojące szyszki kwiatowe — preferuje chłodniejsze stanowiska.",
  },
  {
    id: "wierzba-biala",
    name: "Wierzba biała",
    latinName: "Salix alba",
    category: "drzewo",
    bloomMonths: bm([4, "peak"]),
    colors: ["zolty"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "15–25 m",
    description: "Żółte kotki wczesną wiosną — bardzo szybki wzrost.",
  },
  {
    id: "klon-jesionolistny",
    name: "Klon jesionolistny",
    latinName: "Acer negundo",
    category: "drzewo",
    bloomMonths: bm([4, "peak"], [5, "light"]),
    colors: ["zolty", "czerwony"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "10–15 m",
    description: "Zielono-czerwone kwiaty — odporny na zanieczyszczenia.",
  },
  {
    id: "grab-pospolity-drzew",
    name: "Grab pospolity (drzewo)",
    latinName: "Carpinus betulus",
    category: "drzewo",
    bloomMonths: bm([4, "light"], [5, "peak"]),
    colors: ["zolty"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: true,
    light: ["pelne-slonce", "polcien"],
    height: "15–25 m",
    description: "Kwitnienie niepozorne — żółte liście jesienią.",
  },
  {
    id: "fotinia",
    name: "Fotinia",
    latinName: "Photinia × fraseri",
    category: "krzew",
    bloomMonths: bm([5, "peak"]),
    colors: ["bialy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "2–4 m",
    description: "Białe kwiaty w maju — czerwone młode liście przez cały sezon.",
  },
  {
    id: "jasminowiec",
    name: "Jaśminowiec",
    latinName: "Philadelphus coronarius",
    category: "krzew",
    bloomMonths: bm([5, "peak"], [6, "light"]),
    colors: ["bialy"],
    scent: "strong",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce", "polcien"],
    height: "2–3 m",
    description: "Intensywnie pachnące białe kwiaty w czerwcu.",
  },
  {
    id: "spiraea-japonska",
    name: "Spiraea japońska",
    latinName: "Spiraea japonica",
    category: "krzew",
    bloomMonths: bm([6, "peak"], [7, "light"]),
    colors: ["rozowy", "czerwony"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: true,
    light: ["pelne-slonce"],
    height: "0.5–1 m",
    description: "Różowe kwiaty latem — kompaktowy krzew rabatowy.",
  },
  {
    id: "spiraea-late",
    name: "Tawułka vanhouttei",
    latinName: "Spiraea × vanhouttei",
    category: "krzew",
    bloomMonths: bm([4, "peak"], [5, "light"]),
    colors: ["bialy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: true,
    light: ["pelne-slonce"],
    height: "2–3 m",
    description: "Kaskady białych kwiatów w kwietniu — łukowate pędy.",
  },
  {
    id: "skrzydlak",
    name: "Skrzydlak",
    latinName: "Euonymus alatus",
    category: "krzew",
    bloomMonths: bm([5, "peak"]),
    colors: ["mieszany"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: true,
    light: ["pelne-slonce", "polcien"],
    height: "2–3 m",
    description: "Drobne kwiaty — intensywnie czerwone liście jesienią.",
  },
  {
    id: "deren-kousa",
    name: "Derień kousa",
    latinName: "Cornus kousa",
    category: "krzew",
    bloomMonths: bm([5, "peak"], [6, "light"]),
    colors: ["bialy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: true,
    light: ["pelne-slonce", "polcien"],
    height: "3–5 m",
    description: "Białe kwiaty w maju — czerwone owoce jesienią.",
  },
  {
    id: "roza-okraglolistna",
    name: "Róża okrąglistna",
    latinName: "Rosa spinosissima",
    category: "krzew",
    bloomMonths: bm([5, "peak"], [6, "light"]),
    colors: ["bialy", "zolty", "rozowy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "1–1.5 m",
    description: "Pachnące kwiaty w czerwcu — bardzo mrozoodporna.",
  },
  {
    id: "hortensja-pnaca",
    name: "Hortensja pnąca",
    latinName: "Hydrangea anomala subsp. petiolaris",
    category: "pnacze",
    bloomMonths: bm([6, "peak"], [7, "light"]),
    colors: ["bialy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["polcien", "cien"],
    height: "do 15 m",
    description: "Białe kwiaty latem — pnącze na północne ściany.",
  },
  {
    id: "pigwowiec-japonski",
    name: "Pigwowiec japoński",
    latinName: "Chaenomeles japonica",
    category: "krzew",
    bloomMonths: bm([4, "peak"]),
    colors: ["czerwony", "rozowy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: false,
    light: ["pelne-slonce", "polcien"],
    height: "1–1.5 m",
    description: "Czerwone kwiaty przed liśćmi — niskie, gęste krzewy.",
  },
  {
    id: "cotoneaster",
    name: "Cotoneaster",
    latinName: "Cotoneaster lucidus",
    category: "krzew",
    bloomMonths: bm([5, "peak"], [6, "light"]),
    colors: ["bialy", "rozowy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: true,
    light: ["pelne-slonce"],
    height: "2–3 m",
    description: "Białe kwiaty w maju — czarne jagody jesienią, żywopłot.",
  },
  {
    id: "abelia",
    name: "Abelia",
    latinName: "Abelia × grandiflora",
    category: "krzew",
    bloomMonths: bm([6, "peak"], [7, "light"], [8, "light"], [9, "peak"]),
    colors: ["bialy", "rozowy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "1–2 m",
    description: "Długie kwitnienie od lipca — delikatny zapach.",
  },
  {
    id: "kalina-kuszczowa",
    name: "Kalina kuszczowa",
    latinName: "Viburnum lantana",
    category: "krzew",
    bloomMonths: bm([5, "peak"]),
    colors: ["bialy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: true,
    light: ["pelne-slonce", "polcien"],
    height: "3–5 m",
    description: "Białe kwiaty w maju — czarne jagody i żółte liście jesienią.",
  },
  {
    id: "tawula-nippon",
    name: "Tawułka japońska",
    latinName: "Spiraea nipponica",
    category: "krzew",
    bloomMonths: bm([5, "peak"], [6, "light"]),
    colors: ["bialy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "1–1.5 m",
    description: "Obfite białe kwiaty w maju — niski, gęsty krzew.",
  },
  {
    id: "bluszcz-kolczasty",
    name: "Bluszcz kolczasty",
    latinName: "Hedera helix",
    category: "pnacze",
    bloomMonths: bm([9, "peak"], [10, "light"]),
    colors: ["zolty", "mieszany"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: false,
    light: ["polcien", "cien"],
    height: "do 20 m",
    description: "Żółto-zielone kwiaty jesienią — pokrywa ściany i pnie.",
  },
  {
    id: "euonymus",
    name: "Euonymus",
    latinName: "Euonymus fortunei",
    category: "krzew",
    bloomMonths: bm([5, "peak"], [6, "light"]),
    colors: ["mieszany"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: true,
    light: ["pelne-slonce", "polcien"],
    height: "0.5–1 m",
    description: "Drobne kwiaty — zimozielony runiec lub żywopłot.",
  },
  {
    id: "alchemilla",
    name: "Alchemilka",
    latinName: "Alchemilla mollis",
    category: "bylina",
    bloomMonths: bm([5, "peak"], [6, "light"], [7, "light"]),
    colors: ["zolty", "mieszany"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce", "polcien"],
    height: "30–50 cm",
    description: "Żółto-zielone kwiaty przez całe lato — srebrzyste liście.",
  },
  {
    id: "monarda",
    name: "Monarda",
    latinName: "Monarda didyma",
    category: "bylina",
    bloomMonths: bm([6, "peak"], [7, "light"], [8, "light"]),
    colors: ["czerwony", "rozowy"],
    scent: "strong",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce", "polcien"],
    height: "60–90 cm",
    description: "Czerwone kwiaty latem — intensywny zapach mięty.",
  },
  {
    id: "pulmonaria",
    name: "Miodunka",
    latinName: "Pulmonaria officinalis",
    category: "bylina",
    bloomMonths: bm([4, "peak"], [5, "light"]),
    colors: ["rozowy", "niebieski"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["polcien", "cien"],
    height: "20–30 cm",
    description: "Różowo-niebieskie kwiaty wiosną — plamiste liście.",
  },
  {
    id: "geum",
    name: "Kuklik",
    latinName: "Geum chiloense",
    category: "bylina",
    bloomMonths: bm([5, "peak"], [6, "light"], [7, "light"]),
    colors: ["pomaranczowy", "czerwony", "zolty"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce", "polcien"],
    height: "40–60 cm",
    description: "Pomarańczowe kwiaty od maja — długie kwitnienie.",
  },
  {
    id: "helenium",
    name: "Helenium",
    latinName: "Helenium autumnale",
    category: "bylina",
    bloomMonths: bm([7, "peak"], [8, "light"], [9, "peak"]),
    colors: ["zolty", "pomaranczowy", "czerwony"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "80–120 cm",
    description: "Jesienne kwiaty w odcieniach żółci i czerwieni.",
  },
  {
    id: "heuchera",
    name: "Żurawka",
    latinName: "Heuchera",
    category: "bylina",
    bloomMonths: bm([5, "peak"], [6, "light"]),
    colors: ["bialy", "rozowy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: true,
    light: ["polcien", "cien"],
    height: "30–50 cm",
    description: "Delikatne kwiaty nad kolorowymi liśćmi.",
  },
  {
    id: "sanguisorba",
    name: "Sanguisorba",
    latinName: "Sanguisorba officinalis",
    category: "bylina",
    bloomMonths: bm([6, "peak"], [7, "light"], [8, "light"]),
    colors: ["czerwony", "rozowy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "60–100 cm",
    description: "Czerwone kwiatostany latem — architektoniczna forma.",
  },
  {
    id: "scabiosa",
    name: "Szczyr",
    latinName: "Scabiosa columbaria",
    category: "bylina",
    bloomMonths: bm([6, "peak"], [7, "light"], [8, "light"], [9, "light"]),
    colors: ["niebieski", "fioletowy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "40–60 cm",
    description: "Niebieskie kwiaty całe lato — motyle.",
  },
  {
    id: "trollius",
    name: "Trollius",
    latinName: "Trollius europaeus",
    category: "bylina",
    bloomMonths: bm([5, "peak"], [6, "light"]),
    colors: ["zolty"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["polcien"],
    height: "40–60 cm",
    description: "Złote miski kwiatów w maju — wilgotne stanowiska.",
  },
  {
    id: "coreopsis",
    name: "Coreopsis",
    latinName: "Coreopsis verticillata",
    category: "bylina",
    bloomMonths: bm([6, "peak"], [7, "light"], [8, "light"], [9, "peak"]),
    colors: ["zolty"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "40–60 cm",
    description: "Żółte kwiaty od czerwca do października.",
  },
  {
    id: "gaillardia",
    name: "Gaillardia",
    latinName: "Gaillardia × grandiflora",
    category: "bylina",
    bloomMonths: bm([6, "peak"], [7, "light"], [8, "light"], [9, "peak"]),
    colors: ["czerwony", "zolty", "pomaranczowy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "40–60 cm",
    description: "Dwukolorowe kwiaty całe lato — suszoodporna.",
  },
  {
    id: "penstemon",
    name: "Penstemon",
    latinName: "Penstemon digitalis",
    category: "bylina",
    bloomMonths: bm([6, "peak"], [7, "light"], [8, "light"]),
    colors: ["bialy", "rozowy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "60–90 cm",
    description: "Białe dzwonkowate kwiaty latem.",
  },
  {
    id: "digitalis",
    name: "Naparstnica",
    latinName: "Digitalis purpurea",
    category: "bylina",
    bloomMonths: bm([6, "peak"], [7, "light"]),
    colors: ["rozowy", "fioletowy", "bialy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["polcien"],
    height: "1–1.5 m",
    description: "Wysokie kwiatostany w czerwcu — cień i wilgoć.",
  },
  {
    id: "baptisia",
    name: "Baptisia",
    latinName: "Baptisia australis",
    category: "bylina",
    bloomMonths: bm([5, "peak"], [6, "light"]),
    colors: ["niebieski"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "1–1.5 m",
    description: "Niebieskie kwiaty w maju — głęboki korzeniowy system.",
  },
  {
    id: "veronica",
    name: "Przetacznik długolistny",
    latinName: "Veronica longifolia",
    category: "bylina",
    bloomMonths: bm([6, "peak"], [7, "light"], [8, "light"]),
    colors: ["niebieski", "rozowy", "bialy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "60–90 cm",
    description: "Niebieskie kwiaty latem — wysokie kłosy.",
  },
  {
    id: "wiesiolka",
    name: "Wiesiołek",
    latinName: "Oenothera biennis",
    category: "bylina",
    bloomMonths: bm([6, "peak"], [7, "light"], [8, "light"]),
    colors: ["zolty"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "80–120 cm",
    description: "Żółte kwiaty wieczorem — motyle nocne.",
  },
  {
    id: "geranium-bloody",
    name: "Geranium",
    latinName: "Geranium sanguineum",
    category: "bylina",
    bloomMonths: bm([5, "peak"], [6, "light"], [7, "light"]),
    colors: ["rozowy", "czerwony"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: true,
    light: ["pelne-slonce", "polcien"],
    height: "30–40 cm",
    description: "Różowe kwiaty od maja — czerwone liście jesienią.",
  },
  {
    id: "alstroemeria",
    name: "Alstremeria",
    latinName: "Alstroemeria aurea",
    category: "bylina",
    bloomMonths: bm([6, "peak"], [7, "light"], [8, "light"]),
    colors: ["pomaranczowy", "zolty", "rozowy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce", "polcien"],
    height: "60–80 cm",
    description: "Kolorowe kwiaty latem — okazałe kwiaty cięte.",
  },
  {
    id: "astilbe",
    name: "Astilbe",
    latinName: "Astilbe arendsii",
    category: "bylina",
    bloomMonths: bm([6, "peak"], [7, "light"]),
    colors: ["rozowy", "bialy", "czerwony"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["polcien", "cien"],
    height: "60–90 cm",
    description: "Puszyste kwiatostany w czerwcu — wilgotne cieniste miejsca.",
  },
  {
    id: "epimedium",
    name: "Epimedium",
    latinName: "Epimedium × versicolor",
    category: "bylina",
    bloomMonths: bm([4, "peak"], [5, "light"]),
    colors: ["zolty", "rozowy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: true,
    light: ["polcien", "cien"],
    height: "20–40 cm",
    description: "Delikatne kwiaty wiosną — okazałe liście jesienią.",
  },
  {
    id: "allium-ozdobne",
    name: "Czosnek ozdobny",
    latinName: "Allium giganteum",
    category: "cebula",
    bloomMonths: bm([5, "peak"], [6, "light"]),
    colors: ["fioletowy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "1–1.5 m",
    description: "Fioletowe kule kwiatów w maju — architektoniczna forma.",
  },
  {
    id: "gladiola",
    name: "Gladiola",
    latinName: "Gladiolus",
    category: "cebula",
    bloomMonths: bm([7, "peak"], [8, "light"]),
    colors: ["czerwony", "rozowy", "fioletowy", "bialy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "80–120 cm",
    description: "Wysokie kwiaty latem — wykop bulwy na zimę.",
  },
  {
    id: "freesja",
    name: "Frezja",
    latinName: "Freesia",
    category: "cebula",
    bloomMonths: bm([6, "peak"], [7, "light"]),
    colors: ["zolty", "bialy", "rozowy"],
    scent: "strong",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "30–40 cm",
    description: "Intensywnie pachnące kwiaty — doniczka lub grządka.",
  },
  {
    id: "amaryllis",
    name: "Amarylis",
    latinName: "Hippeastrum",
    category: "cebula",
    bloomMonths: bm([12, "peak"], [1, "light"], [2, "light"]),
    colors: ["czerwony", "rozowy", "bialy"],
    scent: "none",
    beeFriendly: false,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: true,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "40–60 cm",
    description: "Duże kwiaty zimą — wymuszenie w doniczce.",
  },
  {
    id: "scilla",
    name: "Scylla",
    latinName: "Scilla siberica",
    category: "cebula",
    bloomMonths: bm([3, "peak"], [4, "light"]),
    colors: ["niebieski"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce", "polcien"],
    height: "10–15 cm",
    description: "Niebieskie kwiaty wczesną wiosną — naturalizacja w trawniku.",
  },
  {
    id: "brunera",
    name: "Brunnera",
    latinName: "Brunnera macrophylla",
    category: "bylina",
    bloomMonths: bm([4, "peak"], [5, "light"]),
    colors: ["niebieski"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["polcien", "cien"],
    height: "30–40 cm",
    description: "Niebieskie kwiaty w kwietniu — srebrzyste liście.",
  },
  {
    id: "cyclamen",
    name: "Cyklamen",
    latinName: "Cyclamen coum",
    category: "cebula",
    bloomMonths: bm([2, "peak"], [3, "light"]),
    colors: ["rozowy", "bialy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: true,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["polcien"],
    height: "10–15 cm",
    description: "Różowe kwiaty zimą i wczesną wiosną.",
  },
  {
    id: "ixia",
    name: "Ixia",
    latinName: "Ixia",
    category: "cebula",
    bloomMonths: bm([6, "peak"], [7, "light"]),
    colors: ["czerwony", "rozowy", "zolty"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "40–60 cm",
    description: "Kolorowe kwiaty latem — cebulki wymagają wykopu.",
  },
  {
    id: "ranunculus",
    name: "Jaskier",
    latinName: "Ranunculus asiaticus",
    category: "cebula",
    bloomMonths: bm([5, "peak"], [6, "light"]),
    colors: ["czerwony", "rozowy", "zolty", "bialy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "30–40 cm",
    description: "Pełne kwiaty w maju — okazałe kwiaty cięte.",
  },
  {
    id: "wisteria",
    name: "Glicynia chińska",
    latinName: "Wisteria sinensis",
    category: "pnacze",
    bloomMonths: bm([4, "peak"], [5, "light"]),
    colors: ["fioletowy", "bialy", "rozowy"],
    scent: "strong",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "do 10 m",
    description: "Fioletowe grona w maju — intensywny zapach.",
  },
  {
    id: "akebia",
    name: "Akebia",
    latinName: "Akebia quinata",
    category: "pnacze",
    bloomMonths: bm([4, "peak"], [5, "light"]),
    colors: ["fioletowy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: false,
    light: ["pelne-slonce", "polcien"],
    height: "do 8 m",
    description: "Fioletowe kwiaty wiosną — egzotyczne owoce jesienią.",
  },
  {
    id: "campsis",
    name: "Milin",
    latinName: "Campsis radicans",
    category: "pnacze",
    bloomMonths: bm([7, "peak"], [8, "light"], [9, "peak"]),
    colors: ["pomaranczowy", "czerwony"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "do 10 m",
    description: "Pomarańczowe trąbki latem — szybki wzrost.",
  },
  {
    id: "ipomoea",
    name: "Wilec",
    latinName: "Ipomoea purpurea",
    category: "roczna",
    bloomMonths: bm([7, "peak"], [8, "light"], [9, "peak"]),
    colors: ["fioletowy", "rozowy", "bialy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "2–3 m",
    description: "Fioletowe kwiaty latem — roczne pnącze na kratę.",
  },
  {
    id: "celosia",
    name: "Celozja",
    latinName: "Celosia argentea",
    category: "roczna",
    bloomMonths: bm([7, "peak"], [8, "light"], [9, "light"]),
    colors: ["czerwony", "zolty", "rozowy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "30–60 cm",
    description: "Płomienne kwiaty latem — roślina jednoroczna.",
  },
  {
    id: "begonia",
    name: "Begonia",
    latinName: "Begonia semperflorens",
    category: "roczna",
    bloomMonths: bm([6, "peak"], [7, "light"], [8, "light"], [9, "peak"]),
    colors: ["rozowy", "czerwony", "bialy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["polcien"],
    height: "20–30 cm",
    description: "Kwitnienie od czerwca — rabaty w półcieniu.",
  },
  {
    id: "bratek",
    name: "Bratek",
    latinName: "Viola × wittrockiana",
    category: "roczna",
    bloomMonths: bm([4, "peak"], [5, "light"], [9, "peak"], [10, "light"]),
    colors: ["fioletowy", "zolty", "bialy", "niebieski"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce", "polcien"],
    height: "15–25 cm",
    description: "Kwitnienie wiosną i jesienią — mrozoodporny.",
  },
  {
    id: "cosmos",
    name: "Kosmos",
    latinName: "Cosmos bipinnatus",
    category: "roczna",
    bloomMonths: bm([7, "peak"], [8, "light"], [9, "peak"]),
    colors: ["rozowy", "bialy", "fioletowy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "80–120 cm",
    description: "Różowe kwiaty latem — motyle i pszczoły.",
  },
  {
    id: "eschscholzia",
    name: "Kalifornia",
    latinName: "Eschscholzia californica",
    category: "roczna",
    bloomMonths: bm([6, "peak"], [7, "light"], [8, "light"], [9, "peak"]),
    colors: ["pomaranczowy", "zolty"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "30–40 cm",
    description: "Pomarańczowe maki latem — samosiew.",
  },
  {
    id: "nemesia",
    name: "Nemezja",
    latinName: "Nemesia strumosa",
    category: "roczna",
    bloomMonths: bm([5, "peak"], [6, "light"], [7, "light"], [8, "light"]),
    colors: ["niebieski", "rozowy", "bialy", "zolty"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce", "polcien"],
    height: "20–30 cm",
    description: "Kolorowe kwiaty od maja — doniczka i rabata.",
  },
  {
    id: "agastache",
    name: "Agastache",
    latinName: "Agastache foeniculum",
    category: "bylina",
    bloomMonths: bm([7, "peak"], [8, "light"], [9, "peak"]),
    colors: ["fioletowy", "niebieski"],
    scent: "strong",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "60–90 cm",
    description: "Fioletowe kwiaty latem — miodunka dla pszczół.",
  }
];
