import type { BloomIntensity, FloweringPlant } from "./flowering-plants";

function bm(...entries: [number, BloomIntensity][]) {
  return Object.fromEntries(entries) as Partial<Record<number, BloomIntensity>>;
}

/** Faza 2 — nowe gatunki (bez duplikatów z base/extra) */
export const FLOWERING_PLANTS_PHASE2: FloweringPlant[] = [
  {
    id: "migdalowiec",
    name: "Migdałek trójklapowy",
    latinName: "Prunus triloba",
    category: "krzew",
    bloomMonths: bm([4, "peak"]),
    colors: ["rozowy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "2–3 m",
    description: "Obfite różowe kwiaty jak miniatura wiśni — krótkie, intensywne kwitnienie w kwietniu.",
  },
  {
    id: "kosztela-wisniowa",
    name: "Kosztela",
    latinName: "Amelanchier ovalis",
    category: "krzew",
    bloomMonths: bm([4, "peak"], [5, "light"]),
    colors: ["bialy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: true,
    light: ["pelne-slonce", "polcien"],
    height: "2–4 m",
    description: "Białe kwiaty przed liśćmi — niebieskawe jagody i pomarańczowe liście jesienią.",
  },
  {
    id: "dab-bieluty",
    name: "Dąb bieluty",
    latinName: "Quercus pubescens",
    category: "drzewo",
    bloomMonths: bm([4, "light"], [5, "peak"]),
    colors: ["zolty"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: true,
    light: ["pelne-slonce"],
    height: "15–25 m",
    description: "Długowieczne drzewo liściaste — kwitnienie niepozorne, ale miododajne.",
  },
  {
    id: "klon-polny",
    name: "Klon polny",
    latinName: "Acer campestre",
    category: "drzewo",
    bloomMonths: bm([4, "light"], [5, "peak"]),
    colors: ["zolty"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: true,
    light: ["pelne-slonce", "polcien"],
    height: "10–15 m",
    description: "Skromne kwiaty w maju — żółte jesienne przebarwienie, dobre na żywopłot formowany.",
  },
  {
    id: "deren-bialy",
    name: "Dereń biały",
    latinName: "Cornus alba",
    category: "krzew",
    bloomMonths: bm([5, "light"], [6, "peak"]),
    colors: ["bialy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: true,
    light: ["pelne-slonce", "polcien"],
    height: "2–3 m",
    description: "Białe kwiaty i czerwone pędy zimą — ozdobna kora po cięciu.",
  },
  {
    id: "sumak-octowy",
    name: "Sumak octowy",
    latinName: "Rhus typhina",
    category: "krzew",
    bloomMonths: bm([6, "peak"], [7, "light"]),
    colors: ["zolty"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: true,
    light: ["pelne-slonce"],
    height: "3–5 m",
    description: "Żółte kwiaty i czerwone kwiatostany jesienią — intensywne przebarwienie liści.",
  },
  {
    id: "tarnina",
    name: "Tarnina",
    latinName: "Prunus spinosa",
    category: "krzew",
    bloomMonths: bm([3, "peak"], [4, "peak"]),
    colors: ["bialy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "2–4 m",
    description: "Białe kwiaty na nagich gałęzach — jagody na nalewki, kolce na żywopłot.",
  },
  {
    id: "mahonia",
    name: "Mahonia",
    latinName: "Mahonia aquifolium",
    category: "krzew",
    bloomMonths: bm([3, "peak"], [4, "peak"]),
    colors: ["zolty"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: true,
    light: ["polcien", "pelne-slonce"],
    height: "1–1,5 m",
    description: "Żółte kwiaty wczesną wiosną — kolczaste liście, niebieskie jagody.",
  },
  {
    id: "pieris",
    name: "Pieris japoński",
    latinName: "Pieris japonica",
    category: "krzew",
    bloomMonths: bm([3, "peak"], [4, "peak"], [5, "light"]),
    colors: ["bialy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["polcien", "pelne-slonce"],
    height: "1–2 m",
    description: "Białe grona kwiatów — młode liście często czerwone, wymaga kwaśnej gleby.",
  },
  {
    id: "cytisus",
    name: "Storczykowiec",
    latinName: "Cytisus scoparius",
    category: "krzew",
    bloomMonths: bm([5, "peak"], [6, "peak"]),
    colors: ["zolty"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "1,5–2 m",
    description: "Żółte kwiaty na pręcikach — azotują glebę, lubi ubogie, przepuszczalne podłoże.",
  },
  {
    id: "suchodrzew",
    name: "Suchodrzew",
    latinName: "Lonicera × purpusii",
    category: "krzew",
    bloomMonths: bm([2, "peak"], [3, "peak"]),
    colors: ["bialy", "rozowy"],
    scent: "strong",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: true,
    ornamentalFruit: true,
    autumnColor: false,
    light: ["pelne-slonce", "polcien"],
    height: "2–3 m",
    description: "Pachnące kwiaty zimą i wczesną wiosną — jeden z nielicznych krzewów kwitnących w lutym.",
  },
  {
    id: "perukowiec",
    name: "Perukowiec",
    latinName: "Cotinus coggygria",
    category: "krzew",
    bloomMonths: bm([6, "light"], [7, "peak"]),
    colors: ["rozowy", "mieszany"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: true,
    description: "Różowe „puchy” nad liśćmi — intensywne jesienne przebarwienie, efekt dymu nad krzewem.",
    light: ["pelne-slonce"],
    height: "3–5 m",
  },
  {
    id: "glog",
    name: "Głóg dwuszyjkowy",
    latinName: "Crataegus laevigata",
    category: "drzewo",
    bloomMonths: bm([5, "peak"], [6, "light"]),
    colors: ["bialy", "rozowy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "5–8 m",
    description: "Białe lub różowe kwiaty w maju — czerwone owoce dla ptaków, kolce na żywopłot.",
  },
  {
    id: "lwia-paszcza",
    name: "Lwie paszcze",
    latinName: "Antirrhinum majus",
    category: "roczna",
    bloomMonths: bm([6, "peak"], [7, "peak"], [8, "peak"], [9, "light"]),
    colors: ["rozowy", "czerwony", "zolty", "bialy", "pomaranczowy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "30–80 cm",
    description: "Kolorowe kwiaty całe lato — świetne na rabaty i donice.",
  },
  {
    id: "anemona-jesienna",
    name: "Zawilec japoński",
    latinName: "Anemone × hybrida",
    category: "bylina",
    bloomMonths: bm([8, "light"], [9, "peak"], [10, "peak"]),
    colors: ["rozowy", "bialy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["polcien", "pelne-slonce"],
    height: "80–120 cm",
    description: "Delikatne kwiaty jesienią — rozrasta się kłączami, do półcienia.",
  },
  {
    id: "poziomka",
    name: "Poziomka",
    latinName: "Fragaria × ananassa",
    category: "bylina",
    bloomMonths: bm([5, "peak"], [6, "peak"], [7, "light"]),
    colors: ["bialy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "15–25 cm",
    description: "Białe kwiaty i czerwone owoce — rozsada na rabacie lub w donicach.",
  },
  {
    id: "malwa",
    name: "Malwa ogrodowa",
    latinName: "Alcea rosea",
    category: "bylina",
    bloomMonths: bm([6, "peak"], [7, "peak"], [8, "light"]),
    colors: ["rozowy", "bialy", "czerwony", "fioletowy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "150–200 cm",
    description: "Wysokie kłosy kwiatów przy płocie — dwuletnia, wymaga podpór.",
  },
  {
    id: "koniczyna-czerwona",
    name: "Koniczyna czerwona",
    latinName: "Trifolium pratense",
    category: "bylina",
    bloomMonths: bm([5, "peak"], [6, "peak"], [7, "light"]),
    colors: ["czerwony"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "30–50 cm",
    description: "Miododajna roślina łąki — azotuje glebę, do łąki kwietnej i warzywnika.",
  },
  {
    id: "bodziszek",
    name: "Bodziszek",
    latinName: "Geranium sanguineum",
    category: "bylina",
    bloomMonths: bm([5, "peak"], [6, "peak"], [7, "light"]),
    colors: ["rozowy", "czerwony"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: true,
    light: ["pelne-slonce", "polcien"],
    height: "30–40 cm",
    description: "Długie kwitnienie i czerwone jesienne liście — odporny na suszę.",
  },
  {
    id: "zawilec-gajowy",
    name: "Zawilec gajowy",
    latinName: "Anemone nemorosa",
    category: "bylina",
    bloomMonths: bm([3, "peak"], [4, "peak"], [5, "light"]),
    colors: ["bialy", "rozowy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["polcien", "cien"],
    height: "15–25 cm",
    description: "Białe kwiaty w lesie — naturalizuje się w cieniu pod drzewami liściastymi.",
  },
  {
    id: "przetacznik",
    name: "Przetacznik pospolity",
    latinName: "Verbascum densiflorum",
    category: "bylina",
    bloomMonths: bm([6, "peak"], [7, "peak"], [8, "light"]),
    colors: ["zolty"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "120–180 cm",
    description: "Wysokie żółte kwiaty — dla pszczół i motyli, sucho tolerancyjna.",
  },
  {
    id: "mieczyk",
    name: "Mieczyk",
    latinName: "Gladiolus × hortulanus",
    category: "cebula",
    bloomMonths: bm([7, "peak"], [8, "peak"], [9, "light"]),
    colors: ["czerwony", "rozowy", "bialy", "zolty", "fioletowy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "80–120 cm",
    description: "Kłosy kwiatów latem — cebulki wykopuj na zimę lub mulczuj głęboko.",
  },
  {
    id: "kalina-bodnantens",
    name: "Kalina Bodnant",
    latinName: "Viburnum × bodnantense",
    category: "krzew",
    bloomMonths: bm([10, "light"], [11, "peak"], [12, "peak"], [1, "peak"], [2, "peak"], [3, "light"]),
    colors: ["rozowy"],
    scent: "strong",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: true,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce", "polcien"],
    height: "2–3 m",
    description: "Pachnące różowe kwiaty od października do marca — rzadkie zimowe kwitnienie.",
  },
  {
    id: "facelia",
    name: "Facelia",
    latinName: "Phacelia tanacetifolia",
    category: "roczna",
    bloomMonths: bm([6, "peak"], [7, "peak"], [8, "light"]),
    colors: ["niebieski", "fioletowy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "40–60 cm",
    description: "Miododajna roślina okrywowa — siej jako zielony nawóz lub na łące kwietnej.",
  },
  {
    id: "campanula",
    name: "Dzwonek",
    latinName: "Campanula carpatica",
    category: "bylina",
    bloomMonths: bm([5, "peak"], [6, "peak"], [7, "light"]),
    colors: ["niebieski", "bialy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce", "polcien"],
    height: "20–30 cm",
    description: "Niebieskie dzwonki — niska bylina na skalniaki i obrzeża rabat.",
  },
  {
    id: "delphinium",
    name: "Ostrożka",
    latinName: "Delphinium elatum",
    category: "bylina",
    bloomMonths: bm([6, "peak"], [7, "peak"]),
    colors: ["niebieski", "fioletowy", "bialy", "rozowy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "120–180 cm",
    description: "Wysokie kłosy — wymaga podpór i żyznej, przepuszczalnej gleby.",
  },
  {
    id: "enzian",
    name: "Goryczka",
    latinName: "Gentiana acaulis",
    category: "bylina",
    bloomMonths: bm([4, "peak"], [5, "peak"]),
    colors: ["niebieski"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce", "polcien"],
    height: "10–15 cm",
    description: "Intensywnie niebieskie kwiaty — wymaga kwaśnej, wilgotnej gleby na skalniaku.",
  },
  {
    id: "kalmia",
    name: "Kalmia",
    latinName: "Kalmia latifolia",
    category: "krzew",
    bloomMonths: bm([5, "peak"], [6, "peak"]),
    colors: ["rozowy", "bialy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["polcien", "pelne-slonce"],
    height: "1–2 m",
    description: "Różowe kubki kwiatów — kwaśna gleba, chronić przed wiatrem zimowym.",
  },
];
