import { FLOWERING_PLANTS_EXTRA } from "./flowering-plants-extra";
import { FLOWERING_PLANTS_PHASE2 } from "./flowering-plants-phase2";
import { FLOWERING_PLANTS_PHASE3 } from "./flowering-plants-phase3";
import type { HardinessZone } from "./hardiness-zones";

export type PlantCategory =
  | "drzewo"
  | "krzew"
  | "bylina"
  | "pnacze"
  | "roczna"
  | "cebula";

export type FlowerColor =
  | "bialy"
  | "zolty"
  | "czerwony"
  | "rozowy"
  | "fioletowy"
  | "niebieski"
  | "pomaranczowy"
  | "mieszany";

export type LightNeed = "pelne-slonce" | "polcien" | "cien";

export type BloomIntensity = "peak" | "light";

export interface FloweringPlant {
  id: string;
  name: string;
  latinName: string;
  category: PlantCategory;
  /** Miesiące kwitnienia: 1–12, peak = szczyt, light = pojedyncze kwiaty / przedłużone */
  bloomMonths: Partial<Record<number, BloomIntensity>>;
  colors: FlowerColor[];
  scent: "strong" | "mild" | "none";
  beeFriendly: boolean;
  butterflyFriendly: boolean;
  honeyPlant: boolean;
  winterBloom: boolean;
  ornamentalFruit: boolean;
  autumnColor: boolean;
  light: LightNeed[];
  height: string;
  description: string;
  relatedLink?: { href: string; label: string };
}

export interface FloweringCatalogFilters {
  months?: number[];
  monthsMatch?: "any" | "all";
  colors?: FlowerColor[];
  categories?: PlantCategory[];
  scent?: "scented" | "none";
  beeFriendly?: boolean;
  butterflyFriendly?: boolean;
  honeyPlant?: boolean;
  winterBloom?: boolean;
  ornamentalFruit?: boolean;
  autumnColor?: boolean;
  light?: LightNeed[];
  hardinessZones?: HardinessZone[];
  petSafeDog?: boolean;
  petSafeCat?: boolean;
  petSafeChild?: boolean;
}

export const MONTH_LABELS = [
  { num: 1, short: "I", name: "Styczeń", slug: "styczen", locative: "styczniu" },
  { num: 2, short: "II", name: "Luty", slug: "luty", locative: "lutym" },
  { num: 3, short: "III", name: "Marzec", slug: "marzec", locative: "marcu" },
  { num: 4, short: "IV", name: "Kwiecień", slug: "kwiecien", locative: "kwietniu" },
  { num: 5, short: "V", name: "Maj", slug: "maj", locative: "maju" },
  { num: 6, short: "VI", name: "Czerwiec", slug: "czerwiec", locative: "czerwcu" },
  { num: 7, short: "VII", name: "Lipiec", slug: "lipiec", locative: "lipcu" },
  { num: 8, short: "VIII", name: "Sierpień", slug: "sierpien", locative: "sierpniu" },
  { num: 9, short: "IX", name: "Wrzesień", slug: "wrzesien", locative: "wrześniu" },
  { num: 10, short: "X", name: "Październik", slug: "pazdziernik", locative: "październiku" },
  { num: 11, short: "XI", name: "Listopad", slug: "listopad", locative: "listopadzie" },
  { num: 12, short: "XII", name: "Grudzień", slug: "grudzien", locative: "grudniu" },
] as const;

export const MONTH_LOCATIVE_SLUGS: Record<number, string> = {
  1: "styczniu",
  2: "lutym",
  3: "marcu",
  4: "kwietniu",
  5: "maju",
  6: "czerwcu",
  7: "lipcu",
  8: "sierpniu",
  9: "wrzesniu",
  10: "pazdzierniku",
  11: "listopadzie",
  12: "grudniu",
};

export function monthCatalogSlug(monthNum: number): string {
  return `rosliny-kwitnace-w-${MONTH_LOCATIVE_SLUGS[monthNum]}`;
}

export const PLANT_CATEGORIES: Record<
  PlantCategory,
  { label: string; icon: string; plural: string }
> = {
  drzewo: { label: "Drzewo", icon: "🌳", plural: "drzewa" },
  krzew: { label: "Krzew", icon: "🌿", plural: "krzewy" },
  bylina: { label: "Bylina", icon: "🌸", plural: "byliny" },
  pnacze: { label: "Pnącze", icon: "🌺", plural: "pnącza" },
  roczna: { label: "Roczna", icon: "🌼", plural: "rośliny roczne" },
  cebula: { label: "Cebulowa", icon: "🌷", plural: "rośliny cebulowe" },
};

export const FLOWER_COLORS: Record<FlowerColor, { label: string; hex: string }> = {
  bialy: { label: "Biały", hex: "#f8faf8" },
  zolty: { label: "Żółty", hex: "#facc15" },
  czerwony: { label: "Czerwony", hex: "#ef4444" },
  rozowy: { label: "Różowy", hex: "#f472b6" },
  fioletowy: { label: "Fioletowy", hex: "#a855f7" },
  niebieski: { label: "Niebieski", hex: "#3b82f6" },
  pomaranczowy: { label: "Pomarańczowy", hex: "#f97316" },
  mieszany: { label: "Mieszany", hex: "#94a3b8" },
};

export const LIGHT_LABELS: Record<LightNeed, string> = {
  "pelne-slonce": "Pełne słońce",
  polcien: "Półcień",
  cien: "Cień",
};

function bm(...entries: [number, BloomIntensity][]) {
  return Object.fromEntries(entries) as Partial<Record<number, BloomIntensity>>;
}

const FLOWERING_PLANTS_BASE: FloweringPlant[] = [
  {
    id: "hamamelis",
    name: "Oczar wirginijski",
    latinName: "Hamamelis × intermedia",
    category: "krzew",
    bloomMonths: bm([1, "peak"], [2, "peak"], [3, "light"]),
    colors: ["zolty", "pomaranczowy", "czerwony"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: true,
    ornamentalFruit: false,
    autumnColor: true,
    light: ["pelne-slonce", "polcien"],
    height: "2–4 m",
    description: "Kwitnie w środku zimy — żółte lub pomarańczowe kwiaty na nagich gałęziach. Jedna z niewielu roślin kwitnących w styczniu i lutym.",
    relatedLink: { href: "/porownywarka-krzewow", label: "Porównaj krzewy" },
  },
  {
    id: "ciemiernik",
    name: "Ciemiernik",
    latinName: "Helleborus orientalis",
    category: "bylina",
    bloomMonths: bm([2, "peak"], [3, "peak"], [4, "light"]),
    colors: ["bialy", "rozowy", "fioletowy", "mieszany"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: true,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["polcien", "cien"],
    height: "30–50 cm",
    description: "Wczesnowiosenne kwiaty w cieniu — białe, różowe i fioletowe. Zimozielone liście.",
  },
  {
    id: "sniezyczka",
    name: "Śnieżyczka",
    latinName: "Galanthus nivalis",
    category: "cebula",
    bloomMonths: bm([2, "peak"], [3, "peak"]),
    colors: ["bialy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: true,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["polcien", "cien"],
    height: "10–15 cm",
    description: "Pierwsze kwiaty pod koniec zimy — białe dzwoneczki w cieniu drzew.",
  },
  {
    id: "krokus",
    name: "Krokus",
    latinName: "Crocus vernus",
    category: "cebula",
    bloomMonths: bm([3, "peak"], [4, "light"]),
    colors: ["fioletowy", "zolty", "bialy", "mieszany"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce", "polcien"],
    height: "8–12 cm",
    description: "Wczesna wiosna — fioletowe, żółte i białe kielichy. Miododajny dla pszczół.",
  },
  {
    id: "forsycja",
    name: "Forsycja",
    latinName: "Forsythia × intermedia",
    category: "krzew",
    bloomMonths: bm([3, "peak"], [4, "peak"]),
    colors: ["zolty"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce", "polcien"],
    height: "2–3 m",
    description: "Intensywnie żółte kwiaty przed liśćmi — symbol wiosny. Przycinaj po kwitnieniu.",
    relatedLink: { href: "/porownywarka-krzewow/hortensja-vs-forsycja", label: "Forsycja vs hortensja" },
  },
  {
    id: "magnolia",
    name: "Magnolia",
    latinName: "Magnolia × soulangeana",
    category: "drzewo",
    bloomMonths: bm([4, "peak"], [5, "light"]),
    colors: ["rozowy", "bialy", "fioletowy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce", "polcien"],
    height: "4–8 m",
    description: "Wielkie pucharowate kwiaty przed rozwojem liści — efektowna wiosenna ozdoba ogrodu.",
    relatedLink: { href: "/porownywarka-drzew", label: "Porównywarka drzew" },
  },
  {
    id: "wisnia-pilkowana",
    name: "Wiśnia piłkowana",
    latinName: "Prunus serrulata",
    category: "drzewo",
    bloomMonths: bm([4, "peak"], [5, "light"]),
    colors: ["rozowy", "bialy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: true,
    light: ["pelne-slonce"],
    height: "5–8 m",
    description: "Japońska wiśnia ozdobna — obfite różowe kwiaty jak chmura. Jesienne przebarwienie liści.",
    relatedLink: { href: "/porownywarka-drzew", label: "Drzewa do ogrodu" },
  },
  {
    id: "pigwowiec",
    name: "Pigwowiec",
    latinName: "Chaenomeles japonica",
    category: "krzew",
    bloomMonths: bm([4, "peak"], [5, "peak"]),
    colors: ["czerwony", "pomaranczowy", "rozowy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: true,
    light: ["pelne-slonce", "polcien"],
    height: "1–2 m",
    description: "Kwiaty na nagich pędach — czerwone, pomarańczowe. Ozdobne owoce jesienią.",
  },
  {
    id: "bez",
    name: "Bez czarny",
    latinName: "Sambucus nigra",
    category: "krzew",
    bloomMonths: bm([5, "peak"], [6, "peak"], [7, "light"]),
    colors: ["bialy"],
    scent: "strong",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: false,
    light: ["pelne-slonce", "polcien"],
    height: "3–6 m",
    description: "Pachnące białe kwiatostany — miododajne. Owoce na wino i syrop.",
  },
  {
    id: "konwalia",
    name: "Konwalia majowa",
    latinName: "Convallaria majalis",
    category: "bylina",
    bloomMonths: bm([5, "peak"], [6, "light"]),
    colors: ["bialy"],
    scent: "strong",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: false,
    light: ["cien", "polcien"],
    description: "Pachnące dzwoneczki w cieniu — idealna pod drzewa. Trująca!",
    height: "15–25 cm",
  },
  {
    id: "piwonia",
    name: "Piwonia",
    latinName: "Paeonia lactiflora",
    category: "bylina",
    bloomMonths: bm([5, "peak"], [6, "peak"]),
    colors: ["rozowy", "bialy", "czerwony", "fioletowy"],
    scent: "strong",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: true,
    light: ["pelne-slonce"],
    height: "60–100 cm",
    description: "Luksusowe, pachnące kwiaty w maju i czerwcu. Długowieczna bylina.",
  },
  {
    id: "lilak",
    name: "Lilak pospolity",
    latinName: "Syringa vulgaris",
    category: "krzew",
    bloomMonths: bm([5, "peak"], [6, "light"]),
    colors: ["fioletowy", "bialy", "rozowy"],
    scent: "strong",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "3–5 m",
    description: "Intensywnie pachnące grona kwiatów — klasyk polskiego ogrodu. Miododajny.",
  },
  {
    id: "azalia",
    name: "Azalia / Rododendron",
    latinName: "Rhododendron",
    category: "krzew",
    bloomMonths: bm([5, "peak"], [6, "peak"]),
    colors: ["rozowy", "fioletowy", "bialy", "czerwony"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: true,
    light: ["polcien", "cien"],
    height: "0,5–3 m",
    description: "Obfite kwitnienie w półcieniu — kwaśna gleba. Wymaga wilgotnej, przepuszczalnej ziemi.",
  },
  {
    id: "tawula",
    name: "Tawuła japońska",
    latinName: "Spiraea japonica",
    category: "krzew",
    bloomMonths: bm([5, "peak"], [6, "peak"], [7, "light"]),
    colors: ["rozowy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: true,
    light: ["pelne-slonce", "polcien"],
    height: "0,5–1,2 m",
    description: "Różowe kwiatostany przez cały czerwiec. Niska, odporna, na rabaty i żywopłoty.",
    relatedLink: { href: "/porownywarka-krzewow/tawula", label: "Profil tawuły" },
  },
  {
    id: "kalina",
    name: "Kalina koralowa",
    latinName: "Viburnum opulus",
    category: "krzew",
    bloomMonths: bm([5, "peak"], [6, "peak"]),
    colors: ["bialy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: true,
    light: ["pelne-slonce", "polcien"],
    height: "3–5 m",
    description: "Białe kwiaty jak płatki — czerwone owoce jesienią. Rodzima roślina.",
    relatedLink: { href: "/porownywarka-krzewow/kalina", label: "Kalina w porównywarce" },
  },
  {
    id: "roza",
    name: "Róża wielkokwiatowa",
    latinName: "Rosa",
    category: "krzew",
    bloomMonths: bm([6, "peak"], [7, "peak"], [8, "peak"], [9, "light"]),
    colors: ["czerwony", "rozowy", "bialy", "zolty", "pomaranczowy", "mieszany"],
    scent: "strong",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "0,6–1,5 m",
    description: "Królowa ogrodu — powtarzające kwitnienie od czerwca do września. Pachnące odmiany.",
  },
  {
    id: "budleja",
    name: "Budleja Dawida",
    latinName: "Buddleja davidii",
    category: "krzew",
    bloomMonths: bm([6, "peak"], [7, "peak"], [8, "peak"], [9, "peak"]),
    colors: ["fioletowy", "rozowy", "bialy", "niebieski"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "2–3 m",
    description: "Magnes na motyle i pszczoły — kwitnie całe lato. Przycinaj mocno wiosną.",
  },
  {
    id: "hortensja",
    name: "Hortensja bukietowa",
    latinName: "Hydrangea macrophylla",
    category: "krzew",
    bloomMonths: bm([6, "peak"], [7, "peak"], [8, "peak"], [9, "light"]),
    colors: ["niebieski", "rozowy", "bialy", "fioletowy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["polcien"],
    height: "1–2 m",
    description: "Kuliste kwiatostany od czerwca — kolor zależy od pH gleby. Półcień.",
    relatedLink: { href: "/kalendarz-ogrodnika/nawozenie-hortensji", label: "Kiedy nawozić hortensje?" },
  },
  {
    id: "lawenda",
    name: "Lawenda wąskolistna",
    latinName: "Lavandula angustifolia",
    category: "krzew",
    bloomMonths: bm([6, "peak"], [7, "peak"], [8, "light"]),
    colors: ["fioletowy", "niebieski"],
    scent: "strong",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "40–80 cm",
    description: "Pachnące fioletowe kwiaty — miododajna, suszona do domu. Wymaga przepuszczalnej gleby.",
  },
  {
    id: "hibiskus",
    name: "Hibiskus syryjski",
    latinName: "Hibiscus syriacus",
    category: "krzew",
    bloomMonths: bm([7, "peak"], [8, "peak"], [9, "peak"]),
    colors: ["rozowy", "bialy", "fioletowy", "niebieski"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "2–3 m",
    description: "Duże kwiaty jak na tropikach — kwitnie w szczycie lata. Opóźnione wybudzenie wiosną.",
  },
  {
    id: "jezowka",
    name: "Jeżówka purpurowa",
    latinName: "Echinacea purpurea",
    category: "bylina",
    bloomMonths: bm([7, "peak"], [8, "peak"], [9, "peak"]),
    colors: ["rozowy", "fioletowy", "bialy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "60–120 cm",
    description: "Stożkowe kwiatostany — pszczoły i motyle uwielbiają. Odporna i długowieczna.",
  },
  {
    id: "kocanka",
    name: "Kocanka (Echinops)",
    latinName: "Echinops ritro",
    category: "bylina",
    bloomMonths: bm([7, "peak"], [8, "peak"]),
    colors: ["niebieski", "fioletowy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "80–120 cm",
    description: "Kuliste, niebieskie kwiaty — architektoniczna bylina. Sucho toleruje suszę.",
  },
  {
    id: "floks",
    name: "Floks wiechowaty",
    latinName: "Phlox paniculata",
    category: "bylina",
    bloomMonths: bm([7, "peak"], [8, "peak"], [9, "light"]),
    colors: ["bialy", "rozowy", "fioletowy", "czerwony"],
    scent: "strong",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce", "polcien"],
    height: "80–120 cm",
    description: "Pachnące wiechy kwiatów — klasyk rabat letnich. Podlewaj w suszy.",
  },
  {
    id: "lilia",
    name: "Lilia",
    latinName: "Lilium",
    category: "cebula",
    bloomMonths: bm([6, "peak"], [7, "peak"], [8, "light"]),
    colors: ["bialy", "rozowy", "pomaranczowy", "czerwony", "zolty"],
    scent: "strong",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce", "polcien"],
    height: "80–150 cm",
    description: "Eleganckie, intensywnie pachnące kwiaty. Sadź głęboko — 3× wysokość cebuli.",
  },
  {
    id: "glicynia",
    name: "Glicynia",
    latinName: "Wisteria sinensis",
    category: "pnacze",
    bloomMonths: bm([5, "peak"], [6, "peak"]),
    colors: ["fioletowy", "bialy", "rozowy"],
    scent: "strong",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "pnącze 6–10 m",
    description: "Zwisające grona fioletowych kwiatów — pergola lub mur. Wymaga mocnego podparcia.",
  },
  {
    id: "powojnik",
    name: "Powojnik",
    latinName: "Clematis",
    category: "pnacze",
    bloomMonths: bm([5, "light"], [6, "peak"], [7, "peak"], [8, "peak"], [9, "light"]),
    colors: ["fioletowy", "rozowy", "bialy", "niebieski", "czerwony"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: false,
    light: ["pelne-slonce", "polcien"],
    height: "pnącze 2–4 m",
    description: "Królowa pnączy — setki odmian, kwitnienie od maja do września zależnie od grupy.",
  },
  {
    id: "kasztanowiec",
    name: "Kasztanowiec",
    latinName: "Aesculus hippocastanum",
    category: "drzewo",
    bloomMonths: bm([5, "peak"], [6, "peak"]),
    colors: ["bialy", "rozowy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: true,
    light: ["pelne-slonce"],
    height: "15–25 m",
    description: "Świeczki białych kwiatów w maju — charakterystyczne owoce jesienią.",
    relatedLink: { href: "/porownywarka-drzew/kasztan-vs-lipa", label: "Kasztan vs lipa" },
  },
  {
    id: "akacja",
    name: "Akacja biała (robinia)",
    latinName: "Robinia pseudoacacia",
    category: "drzewo",
    bloomMonths: bm([5, "peak"], [6, "peak"]),
    colors: ["bialy"],
    scent: "strong",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "15–25 m",
    description: "Pachnące białe grona — jeden z najlepszych miododajnych. Inwazyjna — ogranicz sadzenie.",
    relatedLink: { href: "/porownywarka-drzew", label: "Porównaj drzewa" },
  },
  {
    id: "lipa",
    name: "Lipa drobnolistna",
    latinName: "Tilia cordata",
    category: "drzewo",
    bloomMonths: bm([6, "peak"], [7, "peak"]),
    colors: ["zolty", "bialy"],
    scent: "strong",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce", "polcien"],
    height: "20–30 m",
    description: "Pachnące kwiaty w lipcu — legendarne miododajne. Alejowe drzewo.",
    relatedLink: { href: "/porownywarka-drzew/dab-vs-lipa", label: "Lipa w porównywarce" },
  },
  {
    id: "deren",
    name: "Deren świdy",
    latinName: "Cornus kousa",
    category: "krzew",
    bloomMonths: bm([5, "peak"], [6, "peak"]),
    colors: ["bialy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: true,
    light: ["pelne-slonce", "polcien"],
    height: "3–5 m",
    description: "Białe „kwiaty” (płatki okwiatu) — różowe owoce jesienią i czerwone liście.",
    relatedLink: { href: "/porownywarka-krzewow/deren", label: "Deren — profil" },
  },
  {
    id: "berberys",
    name: "Berberys Thunberga",
    latinName: "Berberis thunbergii",
    category: "krzew",
    bloomMonths: bm([5, "light"], [6, "peak"]),
    colors: ["zolty"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: true,
    light: ["pelne-slonce"],
    height: "0,5–1,5 m",
    description: "Żółte kwiaty i czerwone jagody — żywopłot lub rabata. Jesienne przebarwienie.",
    relatedLink: { href: "/kalkulator-zywoplotu", label: "Kalkulator żywopłotu" },
  },
  {
    id: "rokitnik",
    name: "Rokitnik",
    latinName: "Hippophae rhamnoides",
    category: "krzew",
    bloomMonths: bm([4, "light"], [5, "peak"]),
    colors: ["zolty", "pomaranczowy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "2–4 m",
    description: "Dyskretne kwiaty, spektakularne pomarańczowe owoce jesienią. Wiatroodporny.",
  },
  {
    id: "rudbeckia",
    name: "Rudbekia",
    latinName: "Rudbeckia fulgida",
    category: "bylina",
    bloomMonths: bm([7, "peak"], [8, "peak"], [9, "peak"]),
    colors: ["zolty", "pomaranczowy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "60–90 cm",
    description: "Złote kwiaty z ciemnym środkiem — kwitnie do października. Odporna na suszę.",
  },
  {
    id: "sedum",
    name: "Rozchodnik (Sedum)",
    latinName: "Sedum spectabile",
    category: "bylina",
    bloomMonths: bm([8, "peak"], [9, "peak"], [10, "light"]),
    colors: ["rozowy", "czerwony"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: true,
    light: ["pelne-slonce"],
    height: "40–60 cm",
    description: "Różowe płaty na jesień — motyle i pszczoły. Sucho toleruje i zimuje bez okrycia.",
  },
  {
    id: "astra",
    name: "Astry chińskie",
    latinName: "Callistephus chinensis",
    category: "roczna",
    bloomMonths: bm([8, "peak"], [9, "peak"], [10, "peak"]),
    colors: ["rozowy", "fioletowy", "bialy", "niebieski", "czerwony"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce", "polcien"],
    height: "40–80 cm",
    description: "Jesienne kwiaty w każdym kolorze — przedłuża sezon kwitnienia ogrodu.",
  },
  {
    id: "chryzantema",
    name: "Chryzantema",
    latinName: "Chrysanthemum",
    category: "bylina",
    bloomMonths: bm([9, "peak"], [10, "peak"], [11, "light"]),
    colors: ["zolty", "bialy", "rozowy", "czerwony", "pomaranczowy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "40–80 cm",
    description: "Jesienne kwitnienie gdy inne rośliny przekwitły — żółte, białe, czerwone odmiany.",
  },
  {
    id: "wrzos",
    name: "Wrzos pospolity",
    latinName: "Calluna vulgaris",
    category: "krzew",
    bloomMonths: bm([8, "peak"], [9, "peak"], [10, "peak"]),
    colors: ["rozowy", "bialy", "fioletowy", "czerwony"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: true,
    light: ["pelne-slonce"],
    height: "20–50 cm",
    description: "Dywan różowych kwiatów jesienią — kwaśna gleba. Miododajny.",
  },
  {
    id: "ozdobna-jablonia",
    name: "Jabłoń ozdobna",
    latinName: "Malus",
    category: "drzewo",
    bloomMonths: bm([4, "peak"], [5, "peak"]),
    colors: ["rozowy", "bialy", "czerwony"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "3–6 m",
    description: "Wiosenne kwiaty i małe ozdobne jabłuszka jesienią. Kompaktowe odmiany do małych ogrodów.",
  },
  {
    id: "narcyz",
    name: "Narcyz",
    latinName: "Narcissus",
    category: "cebula",
    bloomMonths: bm([3, "light"], [4, "peak"], [5, "light"]),
    colors: ["zolty", "bialy", "pomaranczowy"],
    scent: "strong",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce", "polcien"],
    height: "25–45 cm",
    description: "Wiosenne żółte i białe trąby — sadź jesienią w grupach. Pachnące odmiany.",
  },
  {
    id: "tulipan",
    name: "Tulipan",
    latinName: "Tulipa",
    category: "cebula",
    bloomMonths: bm([4, "peak"], [5, "peak"]),
    colors: ["czerwony", "rozowy", "zolty", "bialy", "fioletowy", "pomaranczowy"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "25–60 cm",
    description: "Klasik wiosny — każdy kolor i kształt. Sadzenie cebulek we wrześniu.",
    relatedLink: { href: "/kalendarz-ogrodnika/sadzenie-cebul-kwiatowych", label: "Kiedy sadzić cebulki?" },
  },
  {
    id: "zawiliec",
    name: "Zawilec gajowy",
    latinName: "Anemone nemorosa",
    category: "bylina",
    bloomMonths: bm([4, "peak"], [5, "light"]),
    colors: ["bialy", "rozowy", "niebieski"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["cien", "polcien"],
    height: "10–20 cm",
    description: "Białe kwiaty w lesie — naturalistyczna rabata w cieniu drzew.",
  },
  {
    id: "hosta",
    name: "Hosta",
    latinName: "Hosta",
    category: "bylina",
    bloomMonths: bm([6, "light"], [7, "light"], [8, "light"]),
    colors: ["bialy", "fioletowy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: true,
    light: ["cien", "polcien"],
    height: "30–80 cm",
    description: "Głównie dekoracyjne liście, ale kwiaty białe i fioletowe przyciągają motyle. Król cienia.",
  },
  {
    id: "brzoza",
    name: "Brzoza brodawkowata",
    latinName: "Betula pendula",
    category: "drzewo",
    bloomMonths: bm([4, "peak"], [5, "light"]),
    colors: ["zolty", "mieszany"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: true,
    light: ["pelne-slonce"],
    height: "15–25 m",
    description: "Kocieki (kwiaty męskie) w kwietniu — pyłek miododajny. Biała kora przez cały rok.",
    relatedLink: { href: "/porownywarka-drzew/dab-vs-brzoza", label: "Brzoza vs dąb" },
  },
  {
    id: "leszczyna",
    name: "Leszczyna",
    latinName: "Corylus avellana",
    category: "krzew",
    bloomMonths: bm([2, "peak"], [3, "peak"]),
    colors: ["zolty"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: false,
    light: ["pelne-slonce", "polcien"],
    height: "3–6 m",
    description: "Żółte kocieki w lutym i marc — wczesny pyłek dla pszczół. Orzechy laskowe jesienią.",
  },
  {
    id: "wilczomlecz",
    name: "Wilczomlecz",
    latinName: "Euphorbia",
    category: "bylina",
    bloomMonths: bm([4, "peak"], [5, "peak"], [6, "light"]),
    colors: ["zolty", "mieszany"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: false,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: true,
    light: ["pelne-slonce", "polcien"],
    height: "30–80 cm",
    description: "Żółto-zielone kwiaty wiosną — sukulentny wygląd, odporny. Uwaga: mlecz trujący!",
  },
  {
    id: "klematis-jesien",
    name: "Powojnik jesienny",
    latinName: "Clematis tangutica",
    category: "pnacze",
    bloomMonths: bm([7, "peak"], [8, "peak"], [9, "peak"], [10, "light"]),
    colors: ["zolty"],
    scent: "none",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: true,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "pnącze 3–5 m",
    description: "Żółte dzwonki do października — puszyste nasiona jak puch.",
  },
  {
    id: "werbena",
    name: "Werbena ogrodowa",
    latinName: "Verbena bonariensis",
    category: "roczna",
    bloomMonths: bm([6, "peak"], [7, "peak"], [8, "peak"], [9, "peak"], [10, "light"]),
    colors: ["fioletowy", "rozowy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: true,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "100–150 cm",
    description: "Przezroczyste łodygi z fioletowymi kwiatami — motyle całe lato. Samosieje się.",
  },
  {
    id: "stokrotka",
    name: "Stokrotka wielkokwiatowa",
    latinName: "Leucanthemum × superbum",
    category: "bylina",
    bloomMonths: bm([6, "peak"], [7, "peak"], [8, "light"]),
    colors: ["bialy", "zolty"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce"],
    height: "60–90 cm",
    description: "Białe płatki ze złotym środkiem — klasyczna bylina rabatowa. Długie kwitnienie.",
  },
  {
    id: "liliowiec",
    name: "Liliowiec",
    latinName: "Hemerocallis",
    category: "bylina",
    bloomMonths: bm([6, "peak"], [7, "peak"], [8, "peak"]),
    colors: ["zolty", "pomaranczowy", "czerwony", "rozowy"],
    scent: "mild",
    beeFriendly: true,
    butterflyFriendly: true,
    honeyPlant: false,
    winterBloom: false,
    ornamentalFruit: false,
    autumnColor: false,
    light: ["pelne-slonce", "polcien"],
    height: "50–80 cm",
    description: "Kwiat jednodniowy, ale nowe codziennie — żółte, pomarańczowe, czerwone. Bezobsługowy.",
  },
];

export const FLOWERING_PLANTS: FloweringPlant[] = [
  ...FLOWERING_PLANTS_BASE,
  ...FLOWERING_PLANTS_EXTRA,
  ...FLOWERING_PLANTS_PHASE2,
  ...FLOWERING_PLANTS_PHASE3,
];

export const FLOWERING_PLANTS_LIST: FloweringPlant[] = FLOWERING_PLANTS;

export function plantBloomsInMonth(plant: FloweringPlant, month: number): boolean {
  return month in plant.bloomMonths;
}

export function filterFloweringPlants(
  plants: FloweringPlant[],
  filters: FloweringCatalogFilters
): FloweringPlant[] {
  return plants.filter((plant) => {
    if (filters.months?.length) {
      const match = filters.monthsMatch ?? "any";
      if (match === "all") {
        if (!filters.months.every((m) => plantBloomsInMonth(plant, m))) return false;
      } else {
        if (!filters.months.some((m) => plantBloomsInMonth(plant, m))) return false;
      }
    }
    if (filters.categories?.length && !filters.categories.includes(plant.category)) {
      return false;
    }
    if (filters.colors?.length && !filters.colors.some((c) => plant.colors.includes(c))) {
      return false;
    }
    if (filters.scent === "scented" && plant.scent === "none") return false;
    if (filters.scent === "none" && plant.scent !== "none") return false;
    if (filters.beeFriendly && !plant.beeFriendly) return false;
    if (filters.butterflyFriendly && !plant.butterflyFriendly) return false;
    if (filters.honeyPlant && !plant.honeyPlant) return false;
    if (filters.winterBloom && !plant.winterBloom) return false;
    if (filters.ornamentalFruit && !plant.ornamentalFruit) return false;
    if (filters.autumnColor && !plant.autumnColor) return false;
    if (filters.light?.length && !filters.light.some((l) => plant.light.includes(l))) {
      return false;
    }
    return true;
  });
}

export function sortPlantsByBloomStart(plants: FloweringPlant[]): FloweringPlant[] {
  return [...plants].sort((a, b) => {
    const aStart = Math.min(...Object.keys(a.bloomMonths).map(Number));
    const bStart = Math.min(...Object.keys(b.bloomMonths).map(Number));
    return aStart - bStart;
  });
}

export function getBloomMonthRange(plant: FloweringPlant): { start: number; end: number } | null {
  const months = Object.keys(plant.bloomMonths).map(Number);
  if (months.length === 0) return null;
  return { start: Math.min(...months), end: Math.max(...months) };
}

export const MAIN_FLOWERING_FAQ = [
  {
    question: "Jak znaleźć rośliny kwitnące w wybranym miesiącu?",
    answer:
      "Zaznacz miesiące w filtrze „Kiedy ma kwitnąć?” — domyślnie pokazujemy rośliny kwitnące w dowolnym z wybranych miesięcy. Włącz „we wszystkich miesiącach” aby znaleźć rośliny kwitnące przez cały wybrany okres.",
  },
  {
    question: "Które rośliny kwitną całe lato?",
    answer:
      "Budleja, hortensja, lawenda, jeżówka, werbena i hibiskus syryjski kwitną od czerwca do września. Róża wielkokwiatowa i powojnik mogą kwitnąć jeszcze dłużej przy regularnym usuwaniu przekwitłych kwiatów.",
  },
  {
    question: "Co kwitnie w zimie w Polsce?",
    answer:
      "Oczar wirginijski (styczeń–luty), ciemiernik i śnieżyczka (luty–marzec), leszczyna (luty–marzec). To nieliczne rośliny z widocznym kwitnieniem w chłodzie.",
  },
];
